version: "3.8"

services:
  db:
    image: mysql
    container_name: db_docker_area
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_area
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_area
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
      - dev

  www:
    build: node-server
    container_name: www_docker_area
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./node-server:/opt/app/node-server
    restart: always
    command: npm run start
    env_file: ./node-server/.env
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: