version: "3.8"

services:
  db:
    image: mysql
    container_name: db_docker_area
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_area
    restart: always
    depends_on:
      - db
    ports:
      - 8090:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_area
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8091:80"
    restart: always
    networks:
      - dev

  server:
    build: node-server
    container_name: server_docker_area
    depends_on:
      - db
    ports:
      - "8080:3000"
    volumes:
      - ./node-server:/opt/app/node-server
      - /opt/app/node-server/node_modules
    restart: always
    env_file: ./node-server/.env
    networks:
      - dev

networks:
  dev:

volumes:
  db-data: