name: area
description: AREA Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  dio: ^4.0.6
  formz: ^0.4.1
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  go_router: ^5.1.5
  email_validator: ^2.1.17
  cupertino_icons: ^1.0.2
  flutter_linkify: ^5.0.2
  flutter_riverpod: ^2.0.2
  flutter_secure_storage: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_app_name: ^0.1.1

flutter:
  uses-material-design: true

flutter_app_name:
  name: "AREA"
